---
# test file

- name: Install NTP Server.
  hosts: servers
  vars:
    ntpd_restrict_net:
      - { net: "192.168.1.0", mask: "255.255.255.0" }
      - { net: "192.168.2.0", mask: "255.255.255.0" }
  roles:
    - ansible-role-ntpd
